In [67]:
#video url: https://www.youtube.com/watch?v=4urPuRoT1sE&index=4&list=PL2-dafEMk2A7YdKv4XfKpfbTH5z6rEEj3
#outline: use tensorflow to classify housing prices

In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline

In [69]:
#step1 load data 
df = pd.read_csv('data.csv')

In [70]:
#take a look at the data
df.head()

index    area  bathrooms     price    sq_price
0      0  2104.0        3.0  399900.0  190.066540
1      1  1600.0        3.0  329900.0  206.187500
2      2  2400.0        3.0  369000.0  153.750000
3      3  1416.0        2.0  232000.0  163.841808
4      4  3000.0        4.0  539900.0  179.966667

In [71]:
#feature selection:clean the data. removed the feature that we don't need
df = df.drop(['index','price','sq_price'],axis=1)
#because we are going to predict our own price in this example

In [72]:
#only use the first ten rows in this example. so slice the data
df = df[:10]

In [73]:
df

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [74]:
#step2 add labels -> classification : if the house is a good/bad
#buy depending on the area and the num of bathrooms

#1 = a good buy, 0 = a bad buy 
df.loc[:,('y1')] = [1,1,1,0,0,1,0,1,1,1]
#y2 is the opposite of y1 
df.loc[:,('y2')] = df['y1'] == 0
#conver true/false to int
df.loc[:,('y2')] = df['y2'].astype(int)

In [75]:
df

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

In [76]:
#step3 - prepare data for tensorflow
#conver into tensors, which is a generic versions and matrixs vector
#vectors = a list of numbers (1D tensor)
#matric = a list of list of numbers (2D tensor)
# list of list of list of num (3D tensor)

#convert features to input tensor
inputx = df.loc[:,['area','bathrooms']].as_matrix()

#convert labels to input tensors 

inputy = df.loc[:,['y1','y2']].as_matrix()


In [77]:
inputx

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [78]:
inputy

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [79]:
#step 4 - write out our hyperparameters

learning_rate = 0.000001 #how fast we reach convergence 
training_epochs = 2000 #training times 
display_step = 50 
n_sample = inputy.size 

In [80]:
#step 5- create our computation grapy / neural network
#for feature input tensors. none means any number of examples 
# 2 : 2d feature 
#placeholders are gateway for data into our computation graph
x = tf.placeholder(tf.float32,[None,2])



In [81]:
#create weights
#2x2 float matrix that we will 
#keep updating through the training process
#variable in tf hold and update parameters
#in memory buffers containing tensors

W = tf.Variable(tf.zeros([2,2]))

In [82]:
#add biases. 2 biases for 2 inputs 
# y =mx + b 
b = tf.Variable(tf.zeros([2]))




In [83]:
#multiply our weight by our inputs 
#weights are how we govern how ata flows in our computation graph
# y = w*x + b 
y_value= tf.add(tf.matmul(x,W),b)

In [84]:
#apply softmax to value we just created
#softmax is our activation function
#softmax normalize our value ( conver it to probability)

y = tf.nn.softmax(y_value)


In [85]:
#feed in a matrixof labels 
y_ = tf.placeholder(tf.float32,[None,2])

In [86]:
#step6 - perform training 
#create our cost function (error), mean squared error 
#reduce sum computes the sum of elements across dimensions of 
#a tensor

cost = tf.reduce_sum(tf.pow(y_ - y,2)/(2*n_sample))

In [87]:
#gradient descent

optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


In [88]:
#initialize variables and tensorflow session
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)


Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [101]:
#training loop
for i in range(training_epochs):
    sess.run(optimizer, feed_dict={x: inputx, y_: inputy})
    
    #write out logs of training 
    if (i) %display_step == 0 :
        cc = sess.run(cost,feed_dict={x:inputx, y_:inputy})
        print "Training step:", '%04d' % (i), "cost=", "{:.9f}".format(cc) #, \"W=", sess.run(W), "b=", sess.run(b)

print "Optimization Finished!"
training_cost = sess.run(cost, feed_dict={x: inputx, y_: inputy})
print "Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n'

Training step: 0000 cost= 0.109537274
Training step: 0050 cost= 0.109537214
Training step: 0100 cost= 0.109537140
Training step: 0150 cost= 0.109537080
Training step: 0200 cost= 0.109537005
Training step: 0250 cost= 0.109536931
Training step: 0300 cost= 0.109536871
Training step: 0350 cost= 0.109536797
Training step: 0400 cost= 0.109536737
Training step: 0450 cost= 0.109536670
Training step: 0500 cost= 0.109536596
Training step: 0550 cost= 0.109536536
Training step: 0600 cost= 0.109536454
Training step: 0650 cost= 0.109536402
Training step: 0700 cost= 0.109536327
Training step: 0750 cost= 0.109536260
Training step: 0800 cost= 0.109536201
Training step: 0850 cost= 0.109536119
Training step: 0900 cost= 0.109536044
Training step: 0950 cost= 0.109535985
Training step: 1000 cost= 0.109535910
Training step: 1050 cost= 0.109535851
Training step: 1100 cost= 0.109535784
Training step: 1150 cost= 0.109535709
Training step: 1200 cost= 0.109535642
Training step: 1250 cost= 0.109535567
Training ste

In [102]:
'''
Now the training is done. 
TensorFlow is now holding on to our trained model 
(Which is basically just the defined operations, 
plus the variables W and b that resulted from the training process).
Is a cost value of 0.109537 good or bad? I have no idea. 
At least it's better than the first cost value of 0.114958666. 
Let's use the model on our dataset to see how it does, though:'''
sess.run(y,feed_dict = {x:inputx})

array([[ 0.71123087,  0.28876916],
       [ 0.66498965,  0.33501026],
       [ 0.73654455,  0.26345551],
       [ 0.64717317,  0.3528268 ],
       [ 0.78332436,  0.21667559],
       [ 0.70069939,  0.29930058],
       [ 0.65866619,  0.34133378],
       [ 0.64829433,  0.35170567],
       [ 0.64369309,  0.35630688],
       [ 0.65480596,  0.34519401]], dtype=float32)

In [103]:
'''
on the left is close to 0.7, on the right is close to 0
So It's guessing they're all good houses. 
That makes it get 7/10 correct. Not terribly impressive. 
A model with a hidden layer should do better, I guess.
Btw, this is how I calculated the softmax values in the post:'''

sess.run(tf.nn.softmax([1., 2.]))


array([ 0.26894143,  0.7310586 ], dtype=float32)